require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5.0

# ================ STYLE ===============
Style/StringLiterals:
  Exclude:
    - spec/dummy/db/schema.rb

Style/NumericLiterals:
  Exclude:
    - spec/dummy/db/schema.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/dummy/db/schema.rb

# TODO: Activate later
Style/Documentation:
  Enabled: false

# ================ LAYOUT ==============
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/dummy/db/schema.rb

# ================ LINT ================
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb
  
Lint/ConstantDefinitionInBlock:
  Enabled: false

# ================ Metics ================
Metrics/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - snfoil-rails.gemspec

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/**/*.rb

# ================ Naming ================
Naming/FileName:
  Exclude:
    - lib/snfoil-rails.rb

# ================ RSPEC ================

RSpec/MultipleExpectations:
  Max: 5

Rspec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false