require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.6

# ================ STYLE ===============
Style/StringLiterals:
  Exclude:
    - spec/dummy/db/schema.rb

Style/NumericLiterals:
  Exclude:
    - spec/dummy/db/schema.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/dummy/db/schema.rb

# TODO: Activate later
Style/Documentation:
  Enabled: false

# ================ LAYOUT ==============
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/dummy/db/schema.rb

Layout/LineLength:
  Max: 150

# ================ LINT ================
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*_spec.rb

Lint/ConstantDefinitionInBlock:
  Enabled: false

# ================ Metics ================

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - snfoil-rails.gemspec

Metrics/MethodLength:
  Exclude:
    - spec/dummy/db/**/*.rb

# ================ Naming ================
Naming/FileName:
  Exclude:
    - lib/snfoil-rails.rb

# ================ RSPEC ================

RSpec/FilePath:
  CustomTransform:
    SnFoil: snfoil
    CRUD: crud
    API: api
  Exclude:
    - spec/snfoil/rails/api/concerns/*_spec.rb

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5